# Generated by Django 3.2.9 on 2021-11-26 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0002_receita_pessoas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
