# Generated by Django 3.2.9 on 2021-11-26 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0003_alter_receita_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receita',
            name='pessoas',
        ),
        migrations.AlterField(
            model_name='receita',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
