# Generated by Django 3.2.9 on 2021-12-07 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0010_rename_pessoa_receita_auth_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receita',
            old_name='auth_user',
            new_name='pessoa',
        ),
    ]
